### PR TITLE
78 cannot replace variables with values of type map from another class sometimes

### PR DESCRIPTION
**Pull request by lukasjarosch**

### CODE REVIEW

**Comment by andaryjo** [comment]
this is actually what I tried as well, thinking "if it is type map[string]interface{}, simply support map[string]interface{}" :D

in our testing this worked sometimes but would for some unknown reason result in infinite loops other times. But likely I messed something up. I will try out this fix first thing tomorrow.

**Comment by andaryjo** [comment]
I can also see you removed the duplicate replaceVariables function. It took @alxndr13 and me some time to figure out what that was about. :D

**Comment by lukasjarosch** [comment]
@andaryjo Hm, I've not come across an endless loop. I must admit that I've probably not tested as extensively as you did, so I'm looking forward to your results.

**Comment by lukasjarosch** [comment]
Yeah, the duplicate did somehow end up in main. Really sorry about that :pensive:

**Comment by andaryjo** [comment]
Tested, and with this fix now everything seems to work flawlessly 🚀

**Review by andaryjo — APPROVED** [review]

**Comment by alxndr13** [comment]
> Tested, and with this fix now everything seems to work flawlessly 🚀

I can still trigger the error, lets talk about this once you're awake again 😂

**Review by alxndr13 — APPROVED** [review]

**Pull request merged**
